version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: casanova/api
    container_name: casanova-api
    tty: true
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks: 
      - casanova-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - casanova-network
    
networks:
  casanova-network:
    driver: bridge
